### ISSUE TITLE
Exit after few seconds throwing error: socket hang up

### ISSUE THREAD

**Issue by dwr-studio** [st3b1t/SatoshiTop#13]
#### Environment

- SatoshiTop version: 2.2.2
- NodeJs version: 18.15.0
- OS: 
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

#### Description Proposals or Problems

I'm using Umbrel as node loading the blockchain data from an external mounted drive. When I start the satop command dashboard starts but exits after few seconds throwing error:

```
Error: socket hang up
    at connResetException (node:internal/errors:717:14)
    at Socket.socketCloseListener (node:_http_client:475:25)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12)
```

**Comment by dwr-studio** [comment]
Running it with `sudo `gives me this error:

```
TypeError: Cannot destructure property 'address' of 'data.networkinfo.localaddresses[0]' as it is undefined.
    at Tor.updateData (/usr/local/lib/node_modules/satop/lib/bitcoin/tor.js:19:10)
    at updater (/usr/local/lib/node_modules/satop/lib/bitcoin/tor.js:12:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by st3b1t** [comment]
@dwr-studio may be solved in last version
